INSERT INTO fish_species (
    id, slug, common_name_zh, scientific_name, family_name_zh,
    family_scientific_name, genus_name_zh, genus_scientific_name, appearance,
    size_description, habitat_description, distribution, description, image_path,
    image_alt_text, image_source_url, image_author, image_license_name,
    image_license_url, display_order, created_at, updated_at
) VALUES
    (1, 'carassius-auratus', '鲫', 'Carassius auratus', '鲤科', 'Cyprinidae', '鲫属', 'Carassius',
     '体侧扁，背部较高，鳞片细密，体色常随水色与个体而呈灰褐、银灰或金黄。口端位且无须，背鳍基部较长。',
     '成鱼通常属于小到中等体型；不同水域和养殖条件下，体长与体高差异明显。',
     '适应缓流或静水环境，可在池塘、湖湾、沟渠与河流缓流段活动，常在近岸水草或底质较软的水域觅食。',
     '原产东亚淡水水系，在中国多地常见，并因养殖和放流在其他地区形成分布记录。',
     '鲫是常见淡水鲤科鱼类，食性较杂，利用底栖小动物、植物碎屑和藻类等资源。',
     '/images/fish/carassius-auratus.jpg', '鲫（Carassius auratus）',
     'https://commons.wikimedia.org/wiki/File:Carassius_auratus.jpg', 'Alexander Francis Lydon', 'Public domain',
     'https://creativecommons.org/publicdomain/mark/1.0/', 1, '2026-08-11 00:00:00.000000', '2026-08-11 00:00:00.000000'),
    (2, 'cyprinus-carpio', '鲤', 'Cyprinus carpio', '鲤科', 'Cyprinidae', '鲤属', 'Cyprinus',
     '体形较为粗壮而侧扁，背部隆起，口周有两对须，鳞片较大且排列整齐。体色可由黄褐至灰黑，背鳍基部较长。',
     '成鱼可达到较大的淡水鱼体型，具体大小会随种群、食物和栖息水体而变化。',
     '常利用河流缓流段、湖泊、池塘和水库的底层或近底层，偏好有底泥、植物和遮蔽物的水域。',
     '原产欧亚大陆部分淡水水系，在中国广泛养殖并见于多种自然和人工水体。',
     '鲤以底栖无脊椎动物、植物性食物和有机碎屑等为食，是中国常见的养殖与休闲渔业对象。',
     '/images/fish/cyprinus-carpio.jpg', '鲤（Cyprinus carpio）',
     'https://commons.wikimedia.org/wiki/File:Cyprinus_carpio.jpeg', 'Dezidor', 'CC BY-SA 3.0',
     'https://creativecommons.org/licenses/by-sa/3.0/', 2, '2026-08-11 00:00:00.000000', '2026-08-11 00:00:00.000000'),
    (3, 'ctenopharyngodon-idella', '草鱼', 'Ctenopharyngodon idella', '鲤科', 'Cyprinidae', '草鱼属', 'Ctenopharyngodon',
     '身体呈长纺锤形，头部较宽，吻端圆钝，鳞片大而整齐。体背较深、体侧偏灰黄，口裂端位且无须。',
     '成鱼属于较大体型的淡水鱼；其生长状况受食物、水温和水体条件影响。',
     '多在江河、湖泊、水库和池塘的中下层活动，常在有沉水或挺水植物的开阔水域取食。',
     '原产东亚河流系统，在中国广泛分布，并被引种至许多地区用于养殖和水生植被管理。',
     '草鱼以植物性食物为主，人工养殖中常作为重要的草食性经济鱼类。',
     '/images/fish/ctenopharyngodon-idella.jpg', '草鱼（Ctenopharyngodon idella）',
     'https://commons.wikimedia.org/wiki/File:Ctenopharyngodon_idella.jpg', 'Dezidor', 'CC BY 3.0',
     'https://creativecommons.org/licenses/by/3.0/', 3, '2026-08-11 00:00:00.000000', '2026-08-11 00:00:00.000000'),
    (4, 'mylopharyngodon-piceus', '青鱼', 'Mylopharyngodon piceus', '鲤科', 'Cyprinidae', '青鱼属', 'Mylopharyngodon',
     '身体较长而侧扁，体背与体侧多呈青黑或深灰色，鳞片边缘较深。咽齿强壮，适于压碎带硬壳的食物。',
     '成鱼属于较大体型的淡水鱼，个体体长会因年龄、食物条件和水域生产力而不同。',
     '常见于江河、湖泊和水库等较开阔水体的中下层，也可在大型池塘中生活。',
     '原产东亚，在中国长江流域及以南的养殖和天然水体中均有记录。',
     '青鱼以螺、蚌等底栖动物为重要食物来源，是中国传统淡水养殖中的代表性种类。',
     '/images/fish/mylopharyngodon-piceus.jpg', '青鱼（Mylopharyngodon piceus）',
     'https://commons.wikimedia.org/wiki/File:Mylopharyngodon_piceus.jpg', 'Leo Nico (United States Geological Survey)', 'Public domain',
     'https://creativecommons.org/publicdomain/mark/1.0/', 4, '2026-08-11 00:00:00.000000', '2026-08-11 00:00:00.000000'),
    (5, 'hypophthalmichthys-molitrix', '鲢', 'Hypophthalmichthys molitrix', '鲤科', 'Cyprinidae', '鲢属', 'Hypophthalmichthys',
     '体侧扁、头较大，眼位偏低且靠近头部下缘，体色银白，腹部具明显棱。口裂上翘，鳃耙发达。',
     '成鱼可形成中到较大体型，大小受水体浮游生物资源、密度和生长条件影响。',
     '主要在江河、湖泊、水库和池塘的中上层活动，偏好水体较开阔且浮游生物资源较丰富的环境。',
     '原产东亚淡水水系，在中国广泛分布，也因养殖和引种而出现在其他地区。',
     '鲢以滤食浮游生物为主，是淡水多营养级养殖中常用的滤食性鱼类。',
     '/images/fish/hypophthalmichthys-molitrix.jpg', '鲢（Hypophthalmichthys molitrix）',
     'https://commons.wikimedia.org/wiki/File:Hypophthalmichthys_molitrix_02.jpg', 'Tino Strauss', 'CC BY-SA 3.0',
     'https://creativecommons.org/licenses/by-sa/3.0/', 5, '2026-08-11 00:00:00.000000', '2026-08-11 00:00:00.000000'),
    (6, 'hypophthalmichthys-nobilis', '鳙', 'Hypophthalmichthys nobilis', '鲤科', 'Cyprinidae', '鲢属', 'Hypophthalmichthys',
     '头部宽大，额部隆起，眼位低，体色多为灰黑并有不规则深色斑纹。腹部具棱，口大，鳃耙发达。',
     '成鱼可形成中到较大体型，体型和生长速度会随饵料条件及水域环境而变化。',
     '生活于江河、湖泊、水库和池塘等较开阔的中上层水域，常与其他滤食性鱼类共同利用浮游生物资源。',
     '原产东亚，在中国多地养殖水体和部分自然水系中有分布记录，并被引种至其他地区。',
     '鳙主要滤食浮游动物和其他悬浮颗粒，是中国淡水养殖中常见的经济鱼类。',
     '/images/fish/hypophthalmichthys-nobilis.jpg', '鳙（Hypophthalmichthys nobilis）',
     'https://commons.wikimedia.org/wiki/File:Hypophthalmichthys-nob.jpg', 'Harka, Akos', 'CC BY 3.0',
     'https://creativecommons.org/licenses/by/3.0/', 6, '2026-08-11 00:00:00.000000', '2026-08-11 00:00:00.000000'),
    (7, 'channa-argus', '乌鳢', 'Channa argus', '鳢科', 'Channidae', '鳢属', 'Channa',
     '身体延长近圆筒形，头部宽扁似蛇头，背鳍和臀鳍都很长。体侧常有深色云斑或不规则横纹，口裂大。',
     '成鱼通常为中到较大体型，体长随纬度、食物和水体条件而有明显差别。',
     '适应池塘、湖湾、沟渠、河流缓流段等温暖的静水或缓流环境，常利用水草和岸边遮蔽物伏击。',
     '原产东亚，在中国多地淡水水系分布；因人为转移也在原产区以外出现种群。',
     '乌鳢是肉食性鱼类，以鱼、甲壳动物和水生昆虫等为食，具有较强的耐低氧能力。',
     '/images/fish/channa-argus.jpg', '乌鳢（Channa argus）',
     'https://commons.wikimedia.org/wiki/File:Channa_argus_01.jpg', 'Σ64', 'CC BY 4.0',
     'https://creativecommons.org/licenses/by/4.0/', 7, '2026-08-11 00:00:00.000000', '2026-08-11 00:00:00.000000'),
    (8, 'siniperca-chuatsi', '鳜', 'Siniperca chuatsi', '鳜科', 'Sinipercidae', '鳜属', 'Siniperca',
     '体侧扁，头大口裂宽，背鳍具硬棘，体侧有深色斑块和斜纹。鳞片较小，整体呈灰褐至黄褐色。',
     '成鱼多为中等体型，体长与体重会随着水温、食物鱼资源和生境质量而变化。',
     '多栖息于江河、湖泊和水库的较清洁水域，常在结构复杂、水流较缓或有隐蔽处的区域活动。',
     '原产东亚，在中国多条河流及其相连湖泊、水库中分布。',
     '鳜以鱼类和大型水生动物为主食，是具有较高经济价值的淡水肉食性鱼类。',
     '/images/fish/siniperca-chuatsi.jpg', '鳜（Siniperca chuatsi）',
     'https://commons.wikimedia.org/wiki/File:Siniperca_chuatsi.jpg', 'Fredlyfish4', 'CC BY-SA 4.0',
     'https://creativecommons.org/licenses/by-sa/4.0/', 8, '2026-08-11 00:00:00.000000', '2026-08-11 00:00:00.000000'),
    (9, 'tachysurus-fulvidraco', '黄颡鱼', 'Tachysurus fulvidraco', '鲿科', 'Bagridae', '黄颡鱼属', 'Tachysurus',
     '体表无鳞，头部稍扁，口周有多对须。背鳍和胸鳍具硬棘，体色常为黄褐色并带深色斑纹。',
     '成鱼通常为小到中等体型，体长受水域类型、食物和个体年龄影响。',
     '常在江河、湖泊、水库、池塘和溪流的底层活动，偏好有石块、枯枝或水生植物可供隐蔽的环境。',
     '原产东亚，在中国东部和中部多种淡水水体中有分布记录。',
     '黄颡鱼多在黄昏和夜间觅食，以底栖无脊椎动物和小型水生动物等为食。',
     '/images/fish/tachysurus-fulvidraco.jpg', '黄颡鱼（Tachysurus fulvidraco）',
     'https://commons.wikimedia.org/wiki/File:Tachysurus_fulvidraco_from_the_Lake_Khanka.jpg', 'A. C. Tatarinov', 'CC BY-SA 4.0',
     'https://creativecommons.org/licenses/by-sa/4.0/', 9, '2026-08-11 00:00:00.000000', '2026-08-11 00:00:00.000000'),
    (10, 'megalobrama-amblycephala', '团头鲂', 'Megalobrama amblycephala', '鲤科', 'Cyprinidae', '鲂属', 'Megalobrama',
     '体高而侧扁，背缘隆起，头部较小，口端位。体色常为银灰或青灰，背鳍较高，腹部轮廓圆润。',
     '成鱼为中等体型，个体大小因水域食物条件和养殖管理方式而不同。',
     '可生活在湖泊、河流缓流段、水库和池塘，常利用近岸植物带及开阔水域的食物资源。',
     '原产中国长江中下游相关水系，并被广泛移养到其他适宜的淡水水域。',
     '团头鲂以植物性食物和附着生物等为主，是中国重要的淡水养殖鱼类。',
     '/images/fish/megalobrama-amblycephala.jpg', '团头鲂（Megalobrama amblycephala）',
     'https://commons.wikimedia.org/wiki/File:Megalobrama_amblycephala_Kasumigaura1.jpg', 'Totti', 'CC BY-SA 4.0',
     'https://creativecommons.org/licenses/by-sa/4.0/', 10, '2026-08-11 00:00:00.000000', '2026-08-11 00:00:00.000000'),
    (11, 'culter-alburnus', '翘嘴鲌', 'Culter alburnus', '鲤科', 'Cyprinidae', '鲌属', 'Culter',
     '身体细长且侧扁，背部略隆，吻端尖，口裂大并明显上翘。体侧银白，背部较暗，尾鳍深叉。',
     '成鱼多为中等体型，水体开阔程度、饵料鱼资源和生长阶段都会影响个体大小。',
     '常在江河、湖泊和水库的中上层开阔水域游动，也会在近岸与深水交界处活动。',
     '原产东亚，在中国多种河流、湖泊和水库水系中有分布记录。',
     '翘嘴鲌以小型鱼类和水生动物为主要食物，是常见的淡水掠食性鱼类。',
     '/images/fish/culter-alburnus.jpg', '翘嘴鲌（Culter alburnus）',
     'https://commons.wikimedia.org/wiki/File:Culter_alburnus.jpg', 'A. C. Tatarinov', 'CC BY-SA 4.0',
     'https://creativecommons.org/licenses/by-sa/4.0/', 11, '2026-08-11 00:00:00.000000', '2026-08-11 00:00:00.000000'),
    (12, 'misgurnus-anguillicaudatus', '泥鳅', 'Misgurnus anguillicaudatus', '泥鳅科', 'Cobitidae', '泥鳅属', 'Misgurnus',
     '身体细长呈圆筒形，头部较小，口周有须，体表具细小鳞片并有黏液。体色常为黄褐或灰褐并带斑点。',
     '成鱼通常为小型鱼类，体长会随区域、食物和生长条件而变化。',
     '常生活在池塘、稻田、沟渠、溪流缓流段和湖泊近岸的软泥或细沙底质中，可钻入底泥躲避不利条件。',
     '原产东亚，在中国多数温暖湿润地区的浅水淡水生境中有分布记录，也被带入其他地区。',
     '泥鳅以底栖小型无脊椎动物、有机碎屑和藻类等为食，善于利用浅水底质环境。',
     '/images/fish/misgurnus-anguillicaudatus.jpg', '泥鳅（Misgurnus anguillicaudatus）',
     'https://commons.wikimedia.org/wiki/File:Weather_Loach.jpg', 'PrinceNimblesoft', 'CC0 1.0 Universal',
     'https://creativecommons.org/publicdomain/zero/1.0/', 12, '2026-08-11 00:00:00.000000', '2026-08-11 00:00:00.000000');

INSERT INTO fish_aliases (fish_species_id, alias) VALUES
    (1, '鲫鱼'),
    (2, '鲤鱼'),
    (3, '鲩鱼'),
    (4, '螺蛳青'),
    (5, '白鲢'),
    (6, '胖头鱼'),
    (7, '黑鱼'),
    (8, '桂花鱼'),
    (9, '黄辣丁'),
    (10, '武昌鱼'),
    (11, '白刁'),
    (12, '鳅');

INSERT INTO fish_habitats (fish_species_id, habitat_code) VALUES
    (1, 'RIVER'), (1, 'LAKE'),
    (2, 'RIVER'), (2, 'LAKE'),
    (3, 'RIVER'), (3, 'RESERVOIR'),
    (4, 'RIVER'), (4, 'LAKE'),
    (5, 'RIVER'), (5, 'RESERVOIR'),
    (6, 'LAKE'), (6, 'POND'),
    (7, 'RIVER'), (7, 'POND'),
    (8, 'RIVER'), (8, 'RESERVOIR'),
    (9, 'RIVER'), (9, 'STREAM'),
    (10, 'LAKE'), (10, 'POND'),
    (11, 'RIVER'), (11, 'RESERVOIR'),
    (12, 'POND'), (12, 'STREAM');
